apiVersion: apps/v1
kind: Deployment
metadata:
  name: clasificador-dl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clasificador-dl
  template:
    metadata:
      labels:
        app: clasificador-dl
    spec:
      containers:
      - name: clasificador-dl
        image: acraksm2.azurecr.io/clasificador:v2

        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: clasificador-dl-svc
spec:
  type: LoadBalancer
  selector:
    app: clasificador-dl
  ports:
  - port: 80
    targetPort: 5000


